### ISSUE TITLE
DataTriggers: Support Variables In Markup-Expressions And Values

### ISSUE THREAD

**Issue by warappa** [warappa/XamlCSS#45]
```css
$binding: ""{ Binding RelativeSource={RelativeSource Self}, Path=IsFocused}"";
$value: true;
.field {
    @Data $binding $value
    {
        Background: Green;
        Foreground: White;
    }
}
```

should be possible.
