### ISSUE TITLE
PropertyTriggers: Support Variables In Value-Expressions

### ISSUE THREAD

**Issue by warappa** [warappa/XamlCSS#46]
```css
$property: Text;
$variable: ""SomeValue"";

Button
{
    @Property $property $variable
    {
        BackgroundColor: Red;
    }
}
```
should be possible
